### ISSUE TITLE
Support for ecdh-sha2-nistp256

### ISSUE THREAD

**Issue by Apolo-sys** [warp-tech/russh#210] opened 2023-11-06 12:45 UTC
Would be nice if support added for "ecdh-sha2-nistp256"

**Comment by Eugeny** [comment] 2023-11-06 12:47
<img width="508" alt="Screenshot 2023-11-06 at 13 46 53" src="https://github.com/warp-tech/russh/assets/161476/13a73f28-ef20-41c3-aa0f-71545b983540">

:(

Duplicate of #201

**Comment by Apolo-sys** [comment] 2023-11-17 00:54
Yeah but not ecdh-sha2-nistp256

**Comment by Eugeny** [comment] 2023-11-17 00:59
🤦

**Comment by gleason-m** [comment] 2024-05-07 21:48
+1 on the request for support for the `ecdh-sha2-nistp{256,384,521}` kex algorithms.

@Eugeny, I noticed a comment in curve25519.rs about NIST P-256 formerly being supported. According to blame, this looks like something forked from thrussh (thrussh's source repo won't load for me at the moment, so hard to confirm).
https://github.com/warp-tech/russh/blob/0fc65ea1d45257c0aef2044d333c634a35891402/russh/src/kex/curve25519.rs#L40C1-L42C41

Would it be possible to add back in this implementation? And if there are concerns over the security of the kex, maybe leave these three off of the default preferred safe kex order but still allow a client to opt-in with a custom config?

**Comment by Eugeny** [comment] 2024-05-08 08:36
@gleason-m yes, that's inherited from `thrussh`. Their repo history pre-2020 was wiped and those lines already were there at that point in time.

I don't have a lot of time to work in `russh` right now but I'm hopeful that the [kex trait](https://github.com/warp-tech/russh/blob/main/russh/src/kex/mod.rs#L49) would make it easy for someone to add NIST curves using Curve25519 implementation as a reference

**Closed** 2024-05-10 19:15 UTC
